### ISSUE TITLE
Fails to install from pypi with pip due to missing README.rst

### ISSUE THREAD

**Issue by AndydeCleyre** [albertz/foreground_app_info#1]
Tried with both python2 and python3.

``` bash
$ sudo pip install foreground_app_info

Collecting foreground-app-info
  Using cached foreground_app_info-1.20150501.162721.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-7vli7cfm/foreground-app-info/setup.py", line 20, in <module>
        long_description = open('README.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-7vli7cfm/foreground-app-info
```

**Comment by albertz** [comment]
Oh, thanks for the report. I tested only in the same dir, that's why I didn't recognized this. :) Should be fixed in ccc9f68644. `pip install foreground_app_info` should work now.
